apiVersion: interconnectedcloud.github.io/v1alpha1
kind: Qdrouterd
metadata:
  name: amq-interconnect
spec:
  # Add fields here
  count: 3
  image: quay.io/ajssmith/qpid-dispatch-router:1.6.0
  addresses:
    - prefix: foo
      waypoint: true
    - prefix: bar
      distribution: closest
  listeners:
    - port: 5672
