apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: qdrouterds.interconnectedcloud.github.io
spec:
  group: interconnectedcloud.github.io
  names:
    kind: Qdrouterd
    listKind: QdrouterdList
    plural: qdrouterds
    singular: qdrouterd
    shoreNames:
    - qdr
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
