apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cluster2-inter-router-tls
spec:
  commonName: cluster2-inter-router-default.apps.cluster2.devcluster.openshift.com
  issuerRef:
    name: cluster1-inter-router-ca-issuer
  secretName: cluster2-inter-router-tls

# certificate.certmanager.k8s.io/cluster2-inter-router-tls created
# verify with:
#   oc describe certificate --all-namespaces